// 部门数据
export const departments = [
  { id: "D001", name: "总经办", parent: null, manager: "王总", memberCount: 5, budget: 500000 },
  { id: "D002", name: "财务部", parent: null, manager: "李经理", memberCount: 8, budget: 300000 },
  { id: "D003", name: "市场部", parent: null, manager: "张经理", memberCount: 15, budget: 800000 },
  { id: "D004", name: "研发部", parent: null, manager: "刘经理", memberCount: 25, budget: 1200000 },
  { id: "D005", name: "人事部", parent: null, manager: "陈经理", memberCount: 6, budget: 200000 },
  { id: "D006", name: "销售部", parent: null, manager: "赵经理", memberCount: 18, budget: 600000 },
  { id: "D007", name: "运营部", parent: null, manager: "孙经理", memberCount: 12, budget: 400000 },
  { id: "D008", name: "客服部", parent: "运营部", manager: "周经理", memberCount: 10, budget: 250000 },
]

// 用户数据
export const users = [
  {
    id: "U001",
    name: "王建国",
    username: "wangjg",
    department: "总经办",
    role: "总经理",
    phone: "13800138001",
    email: "wangjg@company.com",
    status: "active",
  },
  {
    id: "U002",
    name: "李明",
    username: "liming",
    department: "财务部",
    role: "财务经理",
    phone: "13800138002",
    email: "liming@company.com",
    status: "active",
  },
  {
    id: "U003",
    name: "张伟",
    username: "zhangwei",
    department: "市场部",
    role: "市场经理",
    phone: "13800138003",
    email: "zhangwei@company.com",
    status: "active",
  },
  {
    id: "U004",
    name: "刘洋",
    username: "liuyang",
    department: "研发部",
    role: "技术总监",
    phone: "13800138004",
    email: "liuyang@company.com",
    status: "active",
  },
  {
    id: "U005",
    name: "陈静",
    username: "chenjing",
    department: "人事部",
    role: "HR经理",
    phone: "13800138005",
    email: "chenjing@company.com",
    status: "active",
  },
  {
    id: "U006",
    name: "赵强",
    username: "zhaoqiang",
    department: "销售部",
    role: "销售经理",
    phone: "13800138006",
    email: "zhaoqiang@company.com",
    status: "active",
  },
  {
    id: "U007",
    name: "孙芳",
    username: "sunfang",
    department: "运营部",
    role: "运营主管",
    phone: "13800138007",
    email: "sunfang@company.com",
    status: "active",
  },
  {
    id: "U008",
    name: "周杰",
    username: "zhoujie",
    department: "客服部",
    role: "客服主管",
    phone: "13800138008",
    email: "zhoujie@company.com",
    status: "inactive",
  },
  {
    id: "U009",
    name: "吴敏",
    username: "wumin",
    department: "财务部",
    role: "会计",
    phone: "13800138009",
    email: "wumin@company.com",
    status: "active",
  },
  {
    id: "U010",
    name: "郑涛",
    username: "zhengtao",
    department: "研发部",
    role: "高级工程师",
    phone: "13800138010",
    email: "zhengtao@company.com",
    status: "active",
  },
  {
    id: "U011",
    name: "冯雪",
    username: "fengxue",
    department: "市场部",
    role: "市场专员",
    phone: "13800138011",
    email: "fengxue@company.com",
    status: "active",
  },
  {
    id: "U012",
    name: "许晓",
    username: "xuxiao",
    department: "销售部",
    role: "销售代表",
    phone: "13800138012",
    email: "xuxiao@company.com",
    status: "active",
  },
]

// 费用类型
export const expenseCategories = [
  {
    id: "C001",
    name: "差旅费",
    code: "CL",
    icon: "fa-plane",
    color: "bg-blue-500",
    parent: null,
    limit: 20000,
    requireInvoice: true,
    status: "active",
  },
  {
    id: "C002",
    name: "办公费",
    code: "BG",
    icon: "fa-print",
    color: "bg-green-500",
    parent: null,
    limit: 5000,
    requireInvoice: true,
    status: "active",
  },
  {
    id: "C003",
    name: "招待费",
    code: "ZD",
    icon: "fa-utensils",
    color: "bg-amber-500",
    parent: null,
    limit: 3000,
    requireInvoice: true,
    status: "active",
  },
  {
    id: "C004",
    name: "交通费",
    code: "JT",
    icon: "fa-car",
    color: "bg-cyan-500",
    parent: null,
    limit: 1000,
    requireInvoice: true,
    status: "active",
  },
  {
    id: "C005",
    name: "培训费",
    code: "PX",
    icon: "fa-graduation-cap",
    color: "bg-purple-500",
    parent: null,
    limit: 15000,
    requireInvoice: true,
    status: "active",
  },
  {
    id: "C006",
    name: "通讯费",
    code: "TX",
    icon: "fa-phone",
    color: "bg-pink-500",
    parent: null,
    limit: 800,
    requireInvoice: true,
    status: "active",
  },
  {
    id: "C007",
    name: "会议费",
    code: "HY",
    icon: "fa-users",
    color: "bg-indigo-500",
    parent: null,
    limit: 10000,
    requireInvoice: true,
    status: "active",
  },
  {
    id: "C008",
    name: "其他费用",
    code: "QT",
    icon: "fa-ellipsis",
    color: "bg-slate-500",
    parent: null,
    limit: 2000,
    requireInvoice: false,
    status: "active",
  },
  {
    id: "C009",
    name: "机票",
    code: "JP",
    icon: "fa-plane-departure",
    color: "bg-blue-400",
    parent: "差旅费",
    limit: 8000,
    requireInvoice: true,
    status: "active",
  },
  {
    id: "C010",
    name: "酒店",
    code: "JD",
    icon: "fa-hotel",
    color: "bg-blue-300",
    parent: "差旅费",
    limit: 1500,
    requireInvoice: true,
    status: "active",
  },
  {
    id: "C011",
    name: "餐饮",
    code: "CY",
    icon: "fa-bowl-food",
    color: "bg-amber-400",
    parent: "招待费",
    limit: 1000,
    requireInvoice: true,
    status: "active",
  },
]

// 预算数据
export const budgets = [
  {
    id: "B001",
    year: "2024",
    department: "市场部",
    category: "差旅费",
    totalAmount: 200000,
    usedAmount: 156000,
    status: "normal",
  },
  {
    id: "B002",
    year: "2024",
    department: "市场部",
    category: "招待费",
    totalAmount: 150000,
    usedAmount: 128000,
    status: "warning",
  },
  {
    id: "B003",
    year: "2024",
    department: "研发部",
    category: "办公费",
    totalAmount: 100000,
    usedAmount: 45000,
    status: "normal",
  },
  {
    id: "B004",
    year: "2024",
    department: "研发部",
    category: "培训费",
    totalAmount: 300000,
    usedAmount: 180000,
    status: "normal",
  },
  {
    id: "B005",
    year: "2024",
    department: "销售部",
    category: "差旅费",
    totalAmount: 250000,
    usedAmount: 230000,
    status: "danger",
  },
  {
    id: "B006",
    year: "2024",
    department: "销售部",
    category: "招待费",
    totalAmount: 180000,
    usedAmount: 95000,
    status: "normal",
  },
  {
    id: "B007",
    year: "2024",
    department: "人事部",
    category: "培训费",
    totalAmount: 80000,
    usedAmount: 32000,
    status: "normal",
  },
  {
    id: "B008",
    year: "2024",
    department: "财务部",
    category: "办公费",
    totalAmount: 50000,
    usedAmount: 28000,
    status: "normal",
  },
  {
    id: "B009",
    year: "2024",
    department: "总经办",
    category: "会议费",
    totalAmount: 120000,
    usedAmount: 78000,
    status: "normal",
  },
  {
    id: "B010",
    year: "2024",
    department: "运营部",
    category: "差旅费",
    totalAmount: 100000,
    usedAmount: 67000,
    status: "normal",
  },
  {
    id: "B011",
    year: "2024",
    department: "客服部",
    category: "通讯费",
    totalAmount: 60000,
    usedAmount: 42000,
    status: "normal",
  },
  {
    id: "B012",
    year: "2024",
    department: "市场部",
    category: "会议费",
    totalAmount: 80000,
    usedAmount: 72000,
    status: "warning",
  },
]

// 费用申请数据
export const expenses = [
  {
    id: "E001",
    code: "FY2024120001",
    title: "北京出差费用申请",
    applicant: "张伟",
    department: "市场部",
    category: "差旅费",
    amount: 8500,
    applyDate: "2024-12-01",
    status: "approved",
    description: "参加行业展会，拜访客户",
  },
  {
    id: "E002",
    code: "FY2024120002",
    title: "客户招待费",
    applicant: "赵强",
    department: "销售部",
    category: "招待费",
    amount: 3200,
    applyDate: "2024-12-02",
    status: "pending",
    description: "招待重要客户晚宴",
  },
  {
    id: "E003",
    code: "FY2024120003",
    title: "办公用品采购",
    applicant: "吴敏",
    department: "财务部",
    category: "办公费",
    amount: 1500,
    applyDate: "2024-12-02",
    status: "approved",
    description: "采购打印纸、文具等办公用品",
  },
  {
    id: "E004",
    code: "FY2024120004",
    title: "技术培训费用",
    applicant: "郑涛",
    department: "研发部",
    category: "培训费",
    amount: 12000,
    applyDate: "2024-12-03",
    status: "pending",
    description: "参加技术架构培训课程",
  },
  {
    id: "E005",
    code: "FY2024120005",
    title: "上海出差",
    applicant: "冯雪",
    department: "市场部",
    category: "差旅费",
    amount: 6800,
    applyDate: "2024-12-03",
    status: "rejected",
    description: "拜访上海区域客户",
    rejectReason: "预算不足，请下月申请",
  },
  {
    id: "E006",
    code: "FY2024120006",
    title: "部门团建活动",
    applicant: "孙芳",
    department: "运营部",
    category: "其他费用",
    amount: 15000,
    applyDate: "2024-12-04",
    status: "pending",
    description: "年度部门团建活动费用",
  },
  {
    id: "E007",
    code: "FY2024120007",
    title: "客户拜访交通费",
    applicant: "许晓",
    department: "销售部",
    category: "交通费",
    amount: 850,
    applyDate: "2024-12-04",
    status: "approved",
    description: "本地客户拜访交通费",
  },
  {
    id: "E008",
    code: "FY2024120008",
    title: "会议室租赁",
    applicant: "王建国",
    department: "总经办",
    category: "会议费",
    amount: 5000,
    applyDate: "2024-12-05",
    status: "approved",
    description: "季度总结会议场地租赁",
  },
  {
    id: "E009",
    code: "FY2024120009",
    title: "手机话费报销",
    applicant: "周杰",
    department: "客服部",
    category: "通讯费",
    amount: 600,
    applyDate: "2024-12-05",
    status: "pending",
    description: "11月份工作手机话费",
  },
  {
    id: "E010",
    code: "FY2024120010",
    title: "新员工培训",
    applicant: "陈静",
    department: "人事部",
    category: "培训费",
    amount: 8000,
    applyDate: "2024-12-06",
    status: "approved",
    description: "Q4新员工入职培训费用",
  },
  {
    id: "E011",
    code: "FY2024110001",
    title: "深圳展会费用",
    applicant: "张伟",
    department: "市场部",
    category: "差旅费",
    amount: 12500,
    applyDate: "2024-11-15",
    status: "approved",
    description: "参加深圳科技展",
  },
  {
    id: "E012",
    code: "FY2024110002",
    title: "软件采购",
    applicant: "刘洋",
    department: "研发部",
    category: "办公费",
    amount: 25000,
    applyDate: "2024-11-20",
    status: "approved",
    description: "开发工具软件采购",
  },
]

// 报销数据
export const reimbursements = [
  {
    id: "R001",
    code: "BX2024120001",
    title: "11月出差报销",
    applicant: "张伟",
    department: "市场部",
    category: "差旅费",
    amount: 8200,
    applyDate: "2024-12-01",
    status: "approved",
    invoiceCount: 12,
  },
  {
    id: "R002",
    code: "BX2024120002",
    title: "客户招待报销",
    applicant: "赵强",
    department: "销售部",
    category: "招待费",
    amount: 2850,
    applyDate: "2024-12-02",
    status: "pending",
    invoiceCount: 5,
  },
  {
    id: "R003",
    code: "BX2024120003",
    title: "办公用品报销",
    applicant: "吴敏",
    department: "财务部",
    category: "办公费",
    amount: 1380,
    applyDate: "2024-12-02",
    status: "approved",
    invoiceCount: 8,
  },
  {
    id: "R004",
    code: "BX2024120004",
    title: "培训费用报销",
    applicant: "郑涛",
    department: "研发部",
    category: "培训费",
    amount: 11800,
    applyDate: "2024-12-03",
    status: "pending",
    invoiceCount: 3,
  },
  {
    id: "R005",
    code: "BX2024120005",
    title: "交通费报销",
    applicant: "许晓",
    department: "销售部",
    category: "交通费",
    amount: 780,
    applyDate: "2024-12-04",
    status: "approved",
    invoiceCount: 15,
  },
  {
    id: "R006",
    code: "BX2024120006",
    title: "会议费报销",
    applicant: "王建国",
    department: "总经办",
    category: "会议费",
    amount: 4800,
    applyDate: "2024-12-05",
    status: "approved",
    invoiceCount: 6,
  },
  {
    id: "R007",
    code: "BX2024120007",
    title: "通讯费报销",
    applicant: "周杰",
    department: "客服部",
    category: "通讯费",
    amount: 580,
    applyDate: "2024-12-05",
    status: "rejected",
    invoiceCount: 2,
    rejectReason: "发票信息不完整",
  },
  {
    id: "R008",
    code: "BX2024120008",
    title: "培训费报销",
    applicant: "陈静",
    department: "人事部",
    category: "培训费",
    amount: 7600,
    applyDate: "2024-12-06",
    status: "pending",
    invoiceCount: 4,
  },
  {
    id: "R009",
    code: "BX2024110001",
    title: "展会费用报销",
    applicant: "张伟",
    department: "市场部",
    category: "差旅费",
    amount: 12000,
    applyDate: "2024-11-18",
    status: "approved",
    invoiceCount: 18,
  },
  {
    id: "R010",
    code: "BX2024110002",
    title: "软件采购报销",
    applicant: "刘洋",
    department: "研发部",
    category: "办公费",
    amount: 24500,
    applyDate: "2024-11-22",
    status: "approved",
    invoiceCount: 2,
  },
]

// 发票数据
export const invoices = [
  {
    id: "I001",
    code: "044001900111",
    type: "增值税专用发票",
    seller: "北京航空票务有限公司",
    amount: 2580,
    taxAmount: 335.4,
    date: "2024-12-01",
    status: "verified",
    category: "差旅费",
  },
  {
    id: "I002",
    code: "044001900112",
    type: "增值税普通发票",
    seller: "上海大酒店",
    amount: 1680,
    taxAmount: 0,
    date: "2024-12-01",
    status: "verified",
    category: "差旅费",
  },
  {
    id: "I003",
    code: "044001900113",
    type: "增值税普通发票",
    seller: "滴滴出行科技有限公司",
    amount: 256,
    taxAmount: 0,
    date: "2024-12-02",
    status: "verified",
    category: "交通费",
  },
  {
    id: "I004",
    code: "044001900114",
    type: "增值税专用发票",
    seller: "办公伙伴商城",
    amount: 1500,
    taxAmount: 195,
    date: "2024-12-02",
    status: "pending",
    category: "办公费",
  },
  {
    id: "I005",
    code: "044001900115",
    type: "增值税普通发票",
    seller: "外婆家餐饮",
    amount: 860,
    taxAmount: 0,
    date: "2024-12-03",
    status: "verified",
    category: "招待费",
  },
  {
    id: "I006",
    code: "044001900116",
    type: "增值税专用发票",
    seller: "华为技术有限公司",
    amount: 12000,
    taxAmount: 1560,
    date: "2024-12-03",
    status: "verified",
    category: "培训费",
  },
  {
    id: "I007",
    code: "044001900117",
    type: "增值税普通发票",
    seller: "中国移动通信",
    amount: 600,
    taxAmount: 0,
    date: "2024-12-04",
    status: "invalid",
    category: "通讯费",
  },
  {
    id: "I008",
    code: "044001900118",
    type: "增值税专用发票",
    seller: "会展中心",
    amount: 5000,
    taxAmount: 650,
    date: "2024-12-04",
    status: "verified",
    category: "会议费",
  },
  {
    id: "I009",
    code: "044001900119",
    type: "增值税普通发票",
    seller: "京东商城",
    amount: 2350,
    taxAmount: 0,
    date: "2024-12-05",
    status: "pending",
    category: "办公费",
  },
  {
    id: "I010",
    code: "044001900120",
    type: "增值税专用发票",
    seller: "南方航空",
    amount: 3200,
    taxAmount: 416,
    date: "2024-12-05",
    status: "verified",
    category: "差旅费",
  },
  {
    id: "I011",
    code: "044001900121",
    type: "增值税普通发票",
    seller: "如家酒店",
    amount: 890,
    taxAmount: 0,
    date: "2024-12-06",
    status: "verified",
    category: "差旅费",
  },
  {
    id: "I012",
    code: "044001900122",
    type: "增值税专用发票",
    seller: "阿里云计算",
    amount: 8600,
    taxAmount: 1118,
    date: "2024-12-06",
    status: "verified",
    category: "办公费",
  },
]

// 审批数据
export const approvals = [
  {
    id: "A001",
    type: "expense",
    code: "FY2024120002",
    title: "客户招待费",
    applicant: "赵强",
    department: "销售部",
    amount: 3200,
    applyDate: "2024-12-02",
    status: "pending",
    step: 1,
    totalSteps: 3,
  },
  {
    id: "A002",
    type: "expense",
    code: "FY2024120004",
    title: "技术培训费用",
    applicant: "郑涛",
    department: "研发部",
    amount: 12000,
    applyDate: "2024-12-03",
    status: "pending",
    step: 2,
    totalSteps: 3,
  },
  {
    id: "A003",
    type: "expense",
    code: "FY2024120006",
    title: "部门团建活动",
    applicant: "孙芳",
    department: "运营部",
    amount: 15000,
    applyDate: "2024-12-04",
    status: "pending",
    step: 1,
    totalSteps: 4,
  },
  {
    id: "A004",
    type: "expense",
    code: "FY2024120009",
    title: "手机话费报销",
    applicant: "周杰",
    department: "客服部",
    amount: 600,
    applyDate: "2024-12-05",
    status: "pending",
    step: 1,
    totalSteps: 2,
  },
  {
    id: "A005",
    type: "reimbursement",
    code: "BX2024120002",
    title: "客户招待报销",
    applicant: "赵强",
    department: "销售部",
    amount: 2850,
    applyDate: "2024-12-02",
    status: "pending",
    step: 2,
    totalSteps: 3,
  },
  {
    id: "A006",
    type: "reimbursement",
    code: "BX2024120004",
    title: "培训费用报销",
    applicant: "郑涛",
    department: "研发部",
    amount: 11800,
    applyDate: "2024-12-03",
    status: "pending",
    step: 1,
    totalSteps: 3,
  },
  {
    id: "A007",
    type: "reimbursement",
    code: "BX2024120008",
    title: "培训费报销",
    applicant: "陈静",
    department: "人事部",
    amount: 7600,
    applyDate: "2024-12-06",
    status: "pending",
    step: 1,
    totalSteps: 2,
  },
]

// 已审批记录
export const approvedRecords = [
  {
    id: "AR001",
    type: "expense",
    code: "FY2024120001",
    title: "北京出差费用申请",
    applicant: "张伟",
    department: "市场部",
    amount: 8500,
    applyDate: "2024-12-01",
    approveDate: "2024-12-02",
    result: "approved",
    opinion: "同意",
  },
  {
    id: "AR002",
    type: "expense",
    code: "FY2024120003",
    title: "办公用品采购",
    applicant: "吴敏",
    department: "财务部",
    amount: 1500,
    applyDate: "2024-12-02",
    approveDate: "2024-12-03",
    result: "approved",
    opinion: "同意，请按规定采购",
  },
  {
    id: "AR003",
    type: "expense",
    code: "FY2024120005",
    title: "上海出差",
    applicant: "冯雪",
    department: "市场部",
    amount: 6800,
    applyDate: "2024-12-03",
    approveDate: "2024-12-04",
    result: "rejected",
    opinion: "本月预算已用完，请下月申请",
  },
  {
    id: "AR004",
    type: "expense",
    code: "FY2024120007",
    title: "客户拜访交通费",
    applicant: "许晓",
    department: "销售部",
    amount: 850,
    applyDate: "2024-12-04",
    approveDate: "2024-12-04",
    result: "approved",
    opinion: "同意",
  },
  {
    id: "AR005",
    type: "expense",
    code: "FY2024120008",
    title: "会议室租赁",
    applicant: "王建国",
    department: "总经办",
    amount: 5000,
    applyDate: "2024-12-05",
    approveDate: "2024-12-05",
    result: "approved",
    opinion: "同意，请做好会议记录",
  },
  {
    id: "AR006",
    type: "reimbursement",
    code: "BX2024120001",
    title: "11月出差报销",
    applicant: "张伟",
    department: "市场部",
    amount: 8200,
    applyDate: "2024-12-01",
    approveDate: "2024-12-02",
    result: "approved",
    opinion: "票据齐全，同意报销",
  },
  {
    id: "AR007",
    type: "reimbursement",
    code: "BX2024120003",
    title: "办公用品报销",
    applicant: "吴敏",
    department: "财务部",
    amount: 1380,
    applyDate: "2024-12-02",
    approveDate: "2024-12-03",
    result: "approved",
    opinion: "同意",
  },
  {
    id: "AR008",
    type: "reimbursement",
    code: "BX2024120007",
    title: "通讯费报销",
    applicant: "周杰",
    department: "客服部",
    amount: 580,
    applyDate: "2024-12-05",
    approveDate: "2024-12-06",
    result: "rejected",
    opinion: "发票信息不完整，请补充",
  },
]

// 角色数据
export const roles = [
  {
    id: "R001",
    name: "超级管理员",
    code: "super_admin",
    description: "系统最高权限",
    userCount: 1,
    status: "active",
    permissions: [
      "预算编制",
      "预算分配",
      "预算调整",
      "预算分析",
      "费用申请",
      "费用查看",
      "费用撤销",
      "报销申请",
      "报销查看",
      "报销撤销",
      "发票录入",
      "发票验真",
      "发票查看",
      "审批处理",
      "审批转办",
      "审批查看",
      "费用报表",
      "预算报表",
      "部门报表",
      "报表导出",
      "用户管理",
      "角色管理",
      "部门管理",
      "费用类别",
      "审批流程",
    ],
  },
  {
    id: "R002",
    name: "财务管理员",
    code: "finance_admin",
    description: "财务模块管理权限",
    userCount: 3,
    status: "active",
    permissions: [
      "预算编制",
      "预算分配",
      "预算调整",
      "预算分析",
      "费用查看",
      "报销查看",
      "发票录入",
      "发票验真",
      "发票查看",
      "审批处理",
      "审批查看",
      "费用报表",
      "预算报表",
      "部门报表",
      "报表导出",
    ],
  },
  {
    id: "R003",
    name: "部门经理",
    code: "dept_manager",
    description: "部门审批权限",
    userCount: 8,
    status: "active",
    permissions: [
      "预算分析",
      "费用申请",
      "费用查看",
      "报销申请",
      "报销查看",
      "发票查看",
      "审批处理",
      "审批转办",
      "审批查看",
      "费用报表",
      "部门报表",
    ],
  },
  {
    id: "R004",
    name: "普通员工",
    code: "employee",
    description: "基础操作权限",
    userCount: 45,
    status: "active",
    permissions: ["费用申请", "费用查看", "费用撤销", "报销申请", "报销查看", "报销撤销", "发票录入", "发票查看"],
  },
  {
    id: "R005",
    name: "审计员",
    code: "auditor",
    description: "报表查看权限",
    userCount: 2,
    status: "active",
    permissions: [
      "预算分析",
      "费用查看",
      "报销查看",
      "发票查看",
      "审批查看",
      "费用报表",
      "预算报表",
      "部门报表",
      "报表导出",
    ],
  },
]

// 审批流程配置
export const workflows = [
  {
    id: "W001",
    name: "费用申请审批流程（大额）",
    type: "费用申请",
    condition: "金额 > 10000",
    steps: [
      { role: "部门主管", action: "审批" },
      { role: "部门经理", action: "审批" },
      { role: "财务经理", action: "审批" },
      { role: "总经理", action: "审批" },
    ],
    status: "active",
  },
  {
    id: "W002",
    name: "费用申请审批流程（中额）",
    type: "费用申请",
    condition: "金额 ≤ 10000",
    steps: [
      { role: "部门主管", action: "审批" },
      { role: "部门经理", action: "审批" },
      { role: "财务主管", action: "审批" },
    ],
    status: "active",
  },
  {
    id: "W003",
    name: "费用申请审批流程（小额）",
    type: "费用申请",
    condition: "金额 ≤ 1000",
    steps: [{ role: "部门主管", action: "审批" }],
    status: "active",
  },
  {
    id: "W004",
    name: "报销审批流程",
    type: "报销申请",
    condition: "全部",
    steps: [
      { role: "部门主管", action: "审批" },
      { role: "财务主管", action: "审批" },
      { role: "财务经理", action: "审批" },
    ],
    status: "active",
  },
  {
    id: "W005",
    name: "预算调整审批流程",
    type: "预算调整",
    condition: "全部",
    steps: [
      { role: "部门经理", action: "审批" },
      { role: "财务经理", action: "审批" },
      { role: "总经理", action: "审批" },
    ],
    status: "active",
  },
]

// 仪表盘统计数据
export const dashboardStats = {
  totalBudget: 3500000,
  usedBudget: 2150000,
  pendingApprovals: 7,
  monthlyExpense: 458000,
  monthlyReimbursement: 385000,
  invoiceCount: 156,
  expenseByCategory: [
    { category: "差旅费", amount: 125000 },
    { category: "办公费", amount: 85000 },
    { category: "招待费", amount: 68000 },
    { category: "培训费", amount: 92000 },
    { category: "交通费", amount: 35000 },
    { category: "其他", amount: 53000 },
  ],
  monthlyTrend: [
    { month: "1月", expense: 320000, budget: 350000 },
    { month: "2月", expense: 280000, budget: 320000 },
    { month: "3月", expense: 360000, budget: 380000 },
    { month: "4月", expense: 340000, budget: 360000 },
    { month: "5月", expense: 390000, budget: 400000 },
    { month: "6月", expense: 420000, budget: 420000 },
    { month: "7月", expense: 380000, budget: 400000 },
    { month: "8月", expense: 350000, budget: 380000 },
    { month: "9月", expense: 410000, budget: 420000 },
    { month: "10月", expense: 440000, budget: 450000 },
    { month: "11月", expense: 480000, budget: 480000 },
    { month: "12月", expense: 458000, budget: 500000 },
  ],
  departmentBudget: [
    { department: "市场部", budget: 800000, used: 680000 },
    { department: "研发部", budget: 1200000, used: 850000 },
    { department: "销售部", budget: 600000, used: 520000 },
    { department: "人事部", budget: 200000, used: 120000 },
    { department: "财务部", budget: 300000, used: 180000 },
    { department: "其他", budget: 400000, used: 300000 },
  ],
}
